### ISSUE TITLE
creating PDF fails

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/integreat-webapp#280]
Clicking on the "Create PDF" button on e.g. the page https://web.integreat-app.de/augsburg/en/german-language yields an error:
![image](https://user-images.githubusercontent.com/5308236/50979234-10d43900-14c4-11e9-9bb1-46ed1f8357b5.png)

**Comment by Schedulaar** [comment]
Thanks for reporting the issue. Its moved to a cms issue: https://github.com/Integreat/cms/issues/895
